/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batch {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'category' : Category,
}
export type Category = { 'class6' : null } |
  { 'class7' : null } |
  { 'class8' : null } |
  { 'class9' : null } |
  { 'neet' : null } |
  { 'class10' : null } |
  { 'class11' : null } |
  { 'class12' : null };
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'subject' : string,
  'description' : string,
  'category' : Category,
  'batchId' : string,
  'videoUrl' : string,
  'uploadedAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBatch' : ActorMethod<[string, string, string, Category], undefined>,
  'deleteBatch' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllBatches' : ActorMethod<[], Array<Batch>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getBatch' : ActorMethod<[string], Batch>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getFiles' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string], Video>,
  'getVideosByBatchId' : ActorMethod<[string], Array<Video>>,
  'getVideosByCategory' : ActorMethod<[Category], Array<Video>>,
  'initialize' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBatch' : ActorMethod<[string, string, string, Category], undefined>,
  'updateVideo' : ActorMethod<
    [string, string, string, string, string, Category, string, string],
    undefined
  >,
  'uploadVideo' : ActorMethod<
    [string, string, string, string, string, Category, string, string],
    undefined
  >,
  'uploadVideoFile' : ActorMethod<[string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];