/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'class6' : IDL.Null,
  'class7' : IDL.Null,
  'class8' : IDL.Null,
  'class9' : IDL.Null,
  'neet' : IDL.Null,
  'class10' : IDL.Null,
  'class11' : IDL.Null,
  'class12' : IDL.Null,
});
export const Time = IDL.Int;
export const Batch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'category' : Category,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'batchId' : IDL.Text,
  'videoUrl' : IDL.Text,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
  'deleteBatch' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getBatch' : IDL.Func([IDL.Text], [Batch], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getFiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
  'getVideosByBatchId' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
  'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
  'updateVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadVideoFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'class6' : IDL.Null,
    'class7' : IDL.Null,
    'class8' : IDL.Null,
    'class9' : IDL.Null,
    'neet' : IDL.Null,
    'class10' : IDL.Null,
    'class11' : IDL.Null,
    'class12' : IDL.Null,
  });
  const Time = IDL.Int;
  const Batch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'category' : Category,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'batchId' : IDL.Text,
    'videoUrl' : IDL.Text,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
    'deleteBatch' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getBatch' : IDL.Func([IDL.Text], [Batch], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getFiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
    'getVideosByBatchId' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
    'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
    'updateVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadVideoFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };